// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type EpisodeDocumentDataSlicesSlice = EpisodeSlice

/**
 * Content for Episode documents
 */
interface EpisodeDocumentData {
  /**
   * Slice Zone field in *Episode*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EpisodeDocumentDataSlicesSlice> /**
   * Meta Description field in *Episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: episode.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: episode.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EpisodeDocumentData>, 'episode', Lang>

export type AllDocumentTypes = EpisodeDocument

/**
 * Primary content in *Episode → Primary*
 */
export interface EpisodeSliceDefaultPrimary {
  /**
   * title field in *Episode → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *Episode → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for Episode Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EpisodeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EpisodeSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Episode*
 */
type EpisodeSliceVariation = EpisodeSliceDefault

/**
 * Episode Shared Slice
 *
 * - **API ID**: `episode`
 * - **Description**: Episode
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EpisodeSlice = prismic.SharedSlice<'episode', EpisodeSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      EpisodeDocument,
      EpisodeDocumentData,
      EpisodeDocumentDataSlicesSlice,
      AllDocumentTypes,
      EpisodeSlice,
      EpisodeSliceDefaultPrimary,
      EpisodeSliceVariation,
      EpisodeSliceDefault,
    }
  }
}
