/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1mbnMC2KGnU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar'
import Link from 'next/link'
import Image from 'next/image'
import { TeamMember } from '@/components/TeamMemeber'

export function Team() {
  return (
    <section className="w-full py-12 text-center md:py-24 lg:py-32">
      <h2 className="mb-8 text-4xl font-bold">Meet Our Team</h2>
      <div className="container mx-auto grid items-center justify-center gap-8 px-4 md:px-6 lg:grid-cols-3 lg:gap-12 xl:grid-cols-3">
        <TeamMember
          name="John Doe"
          description="John is a seasoned software engineer with a passion for building innovative web applications. He has a wealth of experience in full-stack development and loves collaborating with cross-functional teams."
          imageSrc="https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          altText="John Doe"
        />
        <TeamMember
          name="John Doe"
          description="John is a seasoned software engineer with a passion for building innovative web applications. He has a wealth of experience in full-stack development and loves collaborating with cross-functional teams."
          imageSrc="https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          altText="John Doe"
        />
        <TeamMember
          name="John Doe"
          description="John is a seasoned software engineer with a passion for building innovative web applications. He has a wealth of experience in full-stack development and loves collaborating with cross-functional teams."
          imageSrc="https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          altText="John Doe"
        />
        <TeamMember
          name="John Doe"
          description="John is a seasoned software engineer with a passion for building innovative web applications. He has a wealth of experience in full-stack development and loves collaborating with cross-functional teams."
          imageSrc="https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          altText="John Doe"
        />
        <TeamMember
          name="John Doe"
          description="John is a seasoned software engineer with a passion for building innovative web applications. He has a wealth of experience in full-stack development and loves collaborating with cross-functional teams."
          imageSrc="https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          altText="John Doe"
        />
      </div>
    </section>
  )
}

function LinkedinIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}

function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
